{% set name = "language-data" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 7600ef8aa39555145d06c89f0c324bf7dab834ea0b0a439d8243762e3ebad7ec

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools >=60
    - setuptools-scm >=8.0
    - wheel
    - pip
  run:
    - python
    - marisa-trie >=1.1.0

test:
  imports:
    - language_data
    - language_data.name_data
    - language_data.names
    - language_data.registry_parser
    - language_data.util
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/georgkrause/language_data
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Supplementary data about languages used by the langcodes module
  description: |
    language_data is a supplement to the langcodes module,
    for working with standardized codes for human languages.
    It stores the more bulky and hard-to-index data about languages,
    particularly what they are named in various languages.
  dev_url: https://github.com/georgkrause/language_data
  doc_url: https://github.com/georgkrause/language_data/blob/main/README.md

extra:
  recipe-maintainers:
    - thewchan
